version: "3"
services:
  frontend:
    env_file:
      - .env
    build:
      context: ip-info2
      dockerfile: ip-info2/Dockerfile
    container_name: "${DOCKER_CONTAINER_NAME}"
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --openssl-legacy-provider
    restart: always
